# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: "https-lenpaul-github-io-lagrange"

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID:

menu:
  - { name: "Home", url: "" }
  - { name: "About", url: "about.html" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - {
      icon: "github",
      style: "brands",
      link: "https://www.github.com/dennisdunn",
    }
  - {
      icon: "docker",
      style: "brands",
      link: "https://hub.docker.com/u/dennisdunn",
    }
  #- {icon: 'twitter',  style:'brands',  link: 'https://twitter.com/paululele'}
  #- {icon: 'linkedin', style:'brands',  link: 'http://www.linkedin.com/in/lenpaul/'}
  - {
      icon: "facebook",
      style: "brands",
      link: "https://www.facebook.com/dennis.dunn.581",
    }
  - { icon: "envelope", style: "solid", link: "mailto:ansofive@gmail.com" }
  - { icon: "square-rss", style: "solid", link: "/feed.xml" }

# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: "Newer"
  previous_page: "Older"

sharing_button_prompt: "Feel free to share!"

related_posts: "You may also enjoy:"

post_date_prefix: "Written on"
